export interface Pricing {
  planId?:string,
  currency?:string,
  currencySymbol?:string,
  currencyType?:string,
  features?:any[],
  fontAwesome?:string,
  packageCode?:string,
  packageName?:string,
  packageSubtitle?:string,
  paymentPlan?:string,
  paymentPlanCode?:string,
  planPricing?:string,
  docId?:string,
}